@requestUri = "Users"
@baseAddress = "localhost"
@port = 7071

###

# Create a user in a table storage configured in the local.settings.json file
POST http://localhost:7071/api/Users
Content-Type: application/json

{
    "FirstName": "John",
    "LastName": "Le plus fort"
}

###  

#Get the 50 first users

GET http://{{baseAddress}}:{{port}}/api/{{requestUri}}

###

#Get a specific user

GET http://localhost:7071/api/Users/fa556860-d592-44db-bd8a-ba062c005911

###

GET http://localhost:7071/api/Users/
